# Generated by Django 2.2.7 on 2019-11-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('expression', models.CharField(max_length=200)),
                ('noise_function', models.CharField(max_length=20)),
                ('noise', models.FloatField(null=True)),
                ('fineness', models.FloatField()),
                ('x_min_range', models.FloatField()),
                ('x_max_range', models.FloatField()),
                ('comment', models.CharField(default='', max_length=400, null=True)),
            ],
        ),
    ]
