# Generated by Django 5.2.2 on 2025-06-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputquery',
            old_name='pub_date',
            new_name='published_at',
        ),
        migrations.AlterField(
            model_name='inputquery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
