# Generated by Django 2.1.7 on 2019-03-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0002_auto_20190310_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputquery',
            name='comment',
            field=models.CharField(default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='inputquery',
            name='fineness',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputquery',
            name='noise',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='inputquery',
            name='noise_function',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputquery',
            name='x_max_range',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputquery',
            name='x_min_range',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
