# Generated by Django 5.2.2 on 2025-06-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0002_rename_pub_date_inputquery_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputquery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
